import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { queryClient, apiRequest } from "@/lib/queryClient";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { useUserProfile } from "@/hooks/use-user-profile";
import { Shield, Plus, Trash2, Copy, Check, KeyRound, Users, Gift } from "lucide-react";

export default function AccessCodes() {
  const { toast } = useToast();
  const { isAdmin } = useUserProfile();
  const [label, setLabel] = useState("");
  const [tier, setTier] = useState("ultimate");
  const [maxUses, setMaxUses] = useState("1");
  const [copiedId, setCopiedId] = useState<number | null>(null);

  const { data: codes, isLoading } = useQuery<any[]>({ queryKey: ["/api/admin/access-codes"] });

  const createMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest("POST", "/api/admin/access-codes", {
        label: label || null,
        tier,
        maxUses: parseInt(maxUses) || 1,
      });
      return res.json();
    },
    onSuccess: (data: any) => {
      toast({ title: "Access Code Created", description: `Code: ${data.code} — share this with someone to give them full access.` });
      setLabel("");
      queryClient.invalidateQueries({ queryKey: ["/api/admin/access-codes"] });
    },
    onError: (e: any) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  const revokeMutation = useMutation({
    mutationFn: async (id: number) => {
      await apiRequest("DELETE", `/api/admin/access-codes/${id}`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/access-codes"] });
      toast({ title: "Code Revoked", description: "This code can no longer be used." });
    },
  });

  const copyCode = (code: string, id: number) => {
    navigator.clipboard.writeText(code);
    setCopiedId(id);
    toast({ title: "Copied!", description: "Access code copied to clipboard." });
    setTimeout(() => setCopiedId(null), 2000);
  };

  if (!isAdmin) {
    return (
      <div className="flex items-center justify-center h-full p-8">
        <Card className="max-w-md w-full">
          <CardContent className="p-8 text-center">
            <Shield className="w-12 h-12 mx-auto mb-4 text-muted-foreground" />
            <h2 className="text-xl font-bold mb-2">Admin Only</h2>
            <p className="text-muted-foreground">Access codes can only be generated by the account owner.</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  const activeCodes = codes?.filter((c: any) => c.active) || [];
  const usedCodes = codes?.filter((c: any) => !c.active) || [];

  return (
    <div className="p-3 max-w-3xl mx-auto space-y-3">
      <div className="flex items-center gap-3 mb-2">
        <div className="h-10 w-10 rounded-md bg-primary flex items-center justify-center shrink-0">
          <KeyRound className="h-5 w-5 text-primary-foreground" />
        </div>
        <div>
          <h1 className="text-2xl font-bold" data-testid="text-access-codes-title">Access Codes</h1>
          <p className="text-sm text-muted-foreground">Generate codes to give people full access to CreatorOS</p>
        </div>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Gift className="w-5 h-5 text-primary" />
            Generate New Code
          </CardTitle>
          <CardDescription>Create a code that grants full platform access. Only you can generate these.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <Input
              value={label}
              onChange={(e) => setLabel(e.target.value)}
              placeholder="Who is this for? (optional)"
              data-testid="input-access-code-label"
            />
            <Select value={tier} onValueChange={setTier}>
              <SelectTrigger data-testid="select-access-code-tier"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="youtube">YouTube Tier</SelectItem>
                <SelectItem value="starter">Starter Tier</SelectItem>
                <SelectItem value="pro">Pro Tier</SelectItem>
                <SelectItem value="ultimate">Ultimate Tier</SelectItem>
              </SelectContent>
            </Select>
            <Input
              value={maxUses}
              onChange={(e) => setMaxUses(e.target.value)}
              type="number"
              min="1"
              placeholder="Max uses"
              data-testid="input-access-code-max-uses"
            />
          </div>
          <Button
            size="lg"
            onClick={() => createMutation.mutate()}
            disabled={createMutation.isPending}
            className="w-full sm:w-auto"
            data-testid="button-generate-access-code"
          >
            <Plus className="w-4 h-4 mr-2" />
            {createMutation.isPending ? "Generating..." : "Generate Access Code"}
          </Button>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Shield className="w-5 h-5 text-primary" />
            Active Codes ({activeCodes.length})
          </CardTitle>
          <CardDescription>Share these codes with people to grant them access</CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="space-y-2">
              <Skeleton className="h-14 w-full" />
              <Skeleton className="h-14 w-full" />
            </div>
          ) : !activeCodes.length ? (
            <div className="text-center py-8">
              <KeyRound className="w-10 h-10 mx-auto mb-3 text-muted-foreground" />
              <p className="text-muted-foreground">No active codes yet. Generate one above.</p>
            </div>
          ) : (
            <div className="space-y-2">
              {activeCodes.map((c: any) => (
                <div
                  key={c.id}
                  className="flex items-center justify-between gap-3 p-3 rounded-md bg-muted/50 flex-wrap"
                  data-testid={`access-code-row-${c.id}`}
                >
                  <div className="flex items-center gap-3 flex-wrap">
                    <code className="font-mono text-base font-bold tracking-wider" data-testid={`text-access-code-${c.id}`}>
                      {c.code}
                    </code>
                    <Badge variant="outline">{c.tier}</Badge>
                    {c.label && <span className="text-sm text-muted-foreground">{c.label}</span>}
                    <span className="text-xs text-muted-foreground flex items-center gap-1">
                      <Users className="w-3 h-3" />
                      {c.useCount || 0}/{c.maxUses || "unlimited"}
                    </span>
                  </div>
                  <div className="flex items-center gap-1">
                    <Button
                      variant="outline"
                      size="icon"
                      onClick={() => copyCode(c.code, c.id)}
                      data-testid={`button-copy-code-${c.id}`}
                    >
                      {copiedId === c.id ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
                    </Button>
                    <Button
                      variant="ghost"
                      size="icon"
                      onClick={() => revokeMutation.mutate(c.id)}
                      data-testid={`button-revoke-code-${c.id}`}
                    >
                      <Trash2 className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {usedCodes.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="text-base text-muted-foreground">Revoked Codes ({usedCodes.length})</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {usedCodes.map((c: any) => (
                <div key={c.id} className="flex items-center gap-3 p-2 rounded-md opacity-50 flex-wrap">
                  <code className="font-mono text-sm line-through">{c.code}</code>
                  <Badge variant="secondary">{c.tier}</Badge>
                  {c.label && <span className="text-xs text-muted-foreground">{c.label}</span>}
                  <Badge variant="destructive">Revoked</Badge>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
