#!/usr/bin/env bash
# install-hooks.sh
#
# Installs the project's git hooks into .git/hooks/ so they run automatically
# on commit.  Run this once after cloning the repo:
#
#   bash scripts/install-hooks.sh
#
# The source scripts in scripts/ are the authoritative versions; the installed
# hooks simply delegate to them so the hook logic stays under version control.

set -euo pipefail

HOOKS_DIR=".git/hooks"

if [ ! -d "$HOOKS_DIR" ]; then
  echo "ERROR: .git/hooks directory not found. Are you in the repo root?"
  exit 1
fi

install_hook() {
  local name="$1"
  local target="$HOOKS_DIR/$name"

  cat > "$target" << HOOK
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — do not edit directly.
# Edit scripts/${name}.sh and re-run install-hooks.sh.
exec bash "scripts/${name}.sh" "\$@"
HOOK

  chmod +x "$target"
  echo "  Installed: $HOOKS_DIR/$name -> scripts/${name}.sh"
}

echo "Installing git hooks..."
install_hook "pre-commit"
echo "Done. Hooks are active for this clone."
