import { db } from "../db";
import { contentProvenance, disclosureRequirements, videos, channels } from "@shared/schema";
import { eq, and, desc, inArray } from "drizzle-orm";
import { createLogger } from "../lib/logger";
import { getPolicyPack } from "./policy-packs";

const logger = createLogger("ai-disclosure-intelligence");

const AI_CONTENT_INDICATORS = [
  "ai generated", "ai-generated", "generated by ai", "made with ai",
  "ai voice", "ai avatar", "synthetic voice", "deepfake", "synthetic media",
  "text-to-speech", "tts", "ai art", "midjourney", "dall-e", "stable diffusion",
  "ai thumbnail", "ai script", "chatgpt", "claude", "ai-written",
  "machine generated", "computer generated", "neural network",
  "sora", "runway", "pika", "ai video", "ai animation",
];

const AI_ORIGIN_TYPES = ["ai-generated", "ai-assisted", "ai-enhanced"];

export interface AiDisclosureCheck {
  contentId: number;
  platform: string;
  hasAiContent: boolean;
  aiIndicators: string[];
  requiresDisclosure: boolean;
  hasDisclosure: boolean;
  disclosureStatus: "compliant" | "missing" | "partial" | "not_applicable";
  recommendation: string;
  platformMechanism?: string;
}

export async function checkAiDisclosure(
  userId: string,
  contentId: number,
  title: string,
  description: string,
  platform: string,
  originTypes?: string[]
): Promise<AiDisclosureCheck> {
  const fullText = `${title} ${description}`.toLowerCase();

  const detectedIndicators = AI_CONTENT_INDICATORS.filter(ind => fullText.includes(ind));

  const provenanceRecords = await db.select().from(contentProvenance)
    .where(and(
      eq(contentProvenance.userId, userId),
      eq(contentProvenance.contentId, contentId),
    ));

  const hasAiProvenance = provenanceRecords.some(r => AI_ORIGIN_TYPES.includes(r.originType));
  const hasAiOriginInput = originTypes?.some(ot => AI_ORIGIN_TYPES.includes(ot)) || false;

  const hasAiContent = detectedIndicators.length > 0 || hasAiProvenance || hasAiOriginInput;

  const pack = getPolicyPack(platform);
  const requiresDisclosure = hasAiContent && (pack?.aiDisclosure.required || false);

  let hasDisclosure = false;
  if (requiresDisclosure) {
    const disclosureKeywords = ["ai-generated", "made with ai", "ai content", "synthetic content", "altered content", "ai disclosure"];
    hasDisclosure = disclosureKeywords.some(kw => fullText.includes(kw));

    if (!hasDisclosure && pack) {
      hasDisclosure = pack.aiDisclosure.triggerKeywords.some(kw => fullText.includes(kw));
    }
  }

  let disclosureStatus: AiDisclosureCheck["disclosureStatus"] = "not_applicable";
  if (requiresDisclosure) {
    disclosureStatus = hasDisclosure ? "compliant" : "missing";
  }

  let recommendation = "";
  if (disclosureStatus === "missing" && pack) {
    recommendation = `AI-generated content detected. ${pack.aiDisclosure.description}. `;
    if (pack.aiDisclosure.platformMechanism) {
      recommendation += `Use: ${pack.aiDisclosure.platformMechanism}`;
    }
  } else if (disclosureStatus === "compliant") {
    recommendation = "AI content disclosure is properly in place.";
  } else if (!hasAiContent) {
    recommendation = "No AI-generated content detected.";
  }

  return {
    contentId,
    platform,
    hasAiContent,
    aiIndicators: detectedIndicators,
    requiresDisclosure,
    hasDisclosure,
    disclosureStatus,
    recommendation,
    platformMechanism: pack?.aiDisclosure.platformMechanism,
  };
}

export async function scanUserContentForAiDisclosure(userId: string): Promise<AiDisclosureCheck[]> {
  const userChannels = await db.select().from(channels).where(eq(channels.userId, userId));
  if (userChannels.length === 0) return [];

  const channelIds = userChannels.map(c => c.id);
  const userVideos = await db.select().from(videos)
    .where(inArray(videos.channelId, channelIds))
    .orderBy(desc(videos.createdAt))
    .limit(50);

  const results: AiDisclosureCheck[] = [];

  for (const video of userVideos) {
    const platform = video.platform || userChannels.find(c => c.id === video.channelId)?.platform || "youtube";
    const result = await checkAiDisclosure(
      userId,
      video.id,
      video.title || "",
      video.description || "",
      platform,
    );
    if (result.hasAiContent) {
      results.push(result);
    }
  }

  return results;
}

export async function recordProvenance(
  userId: string,
  contentId: number | null,
  contentType: string,
  assetName: string,
  originType: string,
  source?: string,
  licenseType?: string,
  licenseExpiry?: Date,
): Promise<typeof contentProvenance.$inferSelect> {
  let trustScore = 50;

  if (originType === "user-created") trustScore = 90;
  else if (originType === "licensed") trustScore = 85;
  else if (originType === "stock") trustScore = 80;
  else if (originType === "fair-use") trustScore = 60;
  else if (originType === "ai-generated") trustScore = 70;
  else if (originType === "ai-assisted") trustScore = 75;
  else if (originType === "unknown") trustScore = 20;

  const verificationStatus = ["user-created", "licensed"].includes(originType)
    ? "verified"
    : originType === "unknown"
    ? "flagged"
    : "unverified";

  const [record] = await db.insert(contentProvenance).values({
    userId,
    contentId,
    contentType,
    assetName,
    originType,
    source,
    licenseType,
    licenseExpiry,
    verificationStatus,
    trustScore,
    metadata: {},
  }).returning();

  return record;
}

export async function getProvenance(userId: string, contentId?: number): Promise<(typeof contentProvenance.$inferSelect)[]> {
  const conditions = [eq(contentProvenance.userId, userId)];
  if (contentId !== undefined) {
    conditions.push(eq(contentProvenance.contentId, contentId));
  }

  return db.select().from(contentProvenance)
    .where(conditions.length === 1 ? conditions[0] : and(...conditions))
    .orderBy(desc(contentProvenance.createdAt));
}

export async function verifyMediaTrust(
  userId: string,
  contentId: number,
): Promise<{
  overallTrustScore: number;
  assets: Array<{
    assetName: string;
    originType: string;
    trustScore: number;
    verificationStatus: string;
    issues: string[];
  }>;
  compliant: boolean;
  recommendations: string[];
}> {
  const records = await db.select().from(contentProvenance)
    .where(and(
      eq(contentProvenance.userId, userId),
      eq(contentProvenance.contentId, contentId),
    ));

  if (records.length === 0) {
    return {
      overallTrustScore: 50,
      assets: [],
      compliant: true,
      recommendations: ["No provenance records found. Consider documenting asset origins for better compliance tracking."],
    };
  }

  const assets = records.map(r => {
    const issues: string[] = [];
    if (r.verificationStatus === "flagged") issues.push("Asset origin is unverified — may be misleading");
    if (r.originType === "unknown") issues.push("Unknown origin type — cannot verify authenticity");
    if (r.licenseExpiry && new Date(r.licenseExpiry) < new Date()) issues.push("License has expired");
    if (r.trustScore !== null && r.trustScore < 40) issues.push("Low trust score — review asset authenticity");

    return {
      assetName: r.assetName,
      originType: r.originType,
      trustScore: r.trustScore || 50,
      verificationStatus: r.verificationStatus,
      issues,
    };
  });

  const overallTrustScore = Math.round(
    assets.reduce((sum, a) => sum + a.trustScore, 0) / assets.length
  );

  const recommendations: string[] = [];
  const flaggedAssets = assets.filter(a => a.issues.length > 0);
  if (flaggedAssets.length > 0) {
    recommendations.push(`${flaggedAssets.length} asset(s) have issues that need attention`);
  }
  const unknownAssets = assets.filter(a => a.originType === "unknown");
  if (unknownAssets.length > 0) {
    recommendations.push(`${unknownAssets.length} asset(s) have unknown origins — document their provenance`);
  }
  const expiredLicenses = records.filter(r => r.licenseExpiry && new Date(r.licenseExpiry) < new Date());
  if (expiredLicenses.length > 0) {
    recommendations.push(`${expiredLicenses.length} license(s) have expired — renew or replace assets`);
  }

  return {
    overallTrustScore,
    assets,
    compliant: flaggedAssets.length === 0 && overallTrustScore >= 50,
    recommendations,
  };
}
