import { storage } from "../storage";

interface OptimizationResult {
  optimized: boolean;
  summary: string;
  changes: string[];
}

const lastOptimized: Map<string, number> = new Map();
const OPTIMIZE_COOLDOWN_MS = 6 * 60 * 60 * 1000;
const LAST_OPTIMIZED_MAX_SIZE = 500;

function cleanupLastOptimized(): void {
  const cutoff = Date.now() - 24 * 60 * 60 * 1000;
  for (const [key, ts] of Array.from(lastOptimized)) {
    if (ts < cutoff) lastOptimized.delete(key);
  }
  if (lastOptimized.size > LAST_OPTIMIZED_MAX_SIZE) {
    const sorted = Array.from(lastOptimized.entries()).sort((a, b) => a[1] - b[1]);
    const toRemove = sorted.slice(0, lastOptimized.size - LAST_OPTIMIZED_MAX_SIZE);
    for (const [key] of toRemove) lastOptimized.delete(key);
  }
}

const settingsCleanupInterval = setInterval(cleanupLastOptimized, 5 * 60 * 1000);

export function stopSettingsCleanup(): void {
  clearInterval(settingsCleanupInterval);
}

const NICHE_OPTIMAL_SETTINGS: Record<string, Record<string, any>> = {
  gaming: {
    preferredUploadTime: "14:00-18:00",
    thumbnailStyle: "high-energy",
    descriptionLength: "medium",
    tagStrategy: "trending-heavy",
    commentResponseTone: "casual",
    crossPostPlatforms: ["tiktok", "discord"],
    contentCadence: "daily",
  },
  tech: {
    preferredUploadTime: "08:00-12:00",
    thumbnailStyle: "clean-professional",
    descriptionLength: "long",
    tagStrategy: "keyword-optimized",
    commentResponseTone: "informative",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "2-3-per-week",
  },
  vlog: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "personal-authentic",
    descriptionLength: "medium",
    tagStrategy: "discovery-focused",
    commentResponseTone: "friendly",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "weekly",
  },
  education: {
    preferredUploadTime: "06:00-10:00",
    thumbnailStyle: "clear-text-overlay",
    descriptionLength: "long",
    tagStrategy: "search-optimized",
    commentResponseTone: "helpful",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "2-per-week",
  },
  music: {
    preferredUploadTime: "16:00-20:00",
    thumbnailStyle: "artistic",
    descriptionLength: "short",
    tagStrategy: "genre-focused",
    commentResponseTone: "appreciative",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "weekly",
  },
  fitness: {
    preferredUploadTime: "05:00-09:00",
    thumbnailStyle: "high-contrast",
    descriptionLength: "medium",
    tagStrategy: "transformation-focused",
    commentResponseTone: "motivational",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "3-per-week",
  },
  cooking: {
    preferredUploadTime: "11:00-15:00",
    thumbnailStyle: "appetizing-close-up",
    descriptionLength: "long",
    tagStrategy: "recipe-searchable",
    commentResponseTone: "warm",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-per-week",
  },
  beauty: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "glamorous-close-up",
    descriptionLength: "medium",
    tagStrategy: "product-tagged",
    commentResponseTone: "supportive",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "3-per-week",
  },
  fashion: {
    preferredUploadTime: "09:00-13:00",
    thumbnailStyle: "editorial-styled",
    descriptionLength: "medium",
    tagStrategy: "brand-tagged",
    commentResponseTone: "trendy",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  travel: {
    preferredUploadTime: "08:00-12:00",
    thumbnailStyle: "scenic-cinematic",
    descriptionLength: "long",
    tagStrategy: "location-optimized",
    commentResponseTone: "adventurous",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "weekly",
  },
  comedy: {
    preferredUploadTime: "12:00-16:00",
    thumbnailStyle: "expressive-reaction",
    descriptionLength: "short",
    tagStrategy: "viral-optimized",
    commentResponseTone: "witty",
    crossPostPlatforms: ["tiktok", "x", "discord"],
    contentCadence: "3-5-per-week",
  },
  sports: {
    preferredUploadTime: "15:00-19:00",
    thumbnailStyle: "action-shot",
    descriptionLength: "medium",
    tagStrategy: "event-driven",
    commentResponseTone: "enthusiastic",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "3-per-week",
  },
  finance: {
    preferredUploadTime: "07:00-11:00",
    thumbnailStyle: "data-driven-clean",
    descriptionLength: "long",
    tagStrategy: "authority-building",
    commentResponseTone: "professional",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "2-3-per-week",
  },
  crypto: {
    preferredUploadTime: "09:00-13:00",
    thumbnailStyle: "bold-numbers",
    descriptionLength: "medium",
    tagStrategy: "trending-ticker",
    commentResponseTone: "analytical",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "daily",
  },
  asmr: {
    preferredUploadTime: "20:00-00:00",
    thumbnailStyle: "soft-ambient",
    descriptionLength: "short",
    tagStrategy: "trigger-tagged",
    commentResponseTone: "gentle",
    crossPostPlatforms: ["tiktok"],
    contentCadence: "2-3-per-week",
  },
  diy: {
    preferredUploadTime: "09:00-13:00",
    thumbnailStyle: "before-after-split",
    descriptionLength: "long",
    tagStrategy: "how-to-searchable",
    commentResponseTone: "encouraging",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "weekly",
  },
  crafts: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "colorful-result",
    descriptionLength: "long",
    tagStrategy: "material-tagged",
    commentResponseTone: "encouraging",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-per-week",
  },
  pets: {
    preferredUploadTime: "11:00-15:00",
    thumbnailStyle: "cute-close-up",
    descriptionLength: "short",
    tagStrategy: "breed-tagged",
    commentResponseTone: "playful",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "3-5-per-week",
  },
  animals: {
    preferredUploadTime: "11:00-15:00",
    thumbnailStyle: "nature-close-up",
    descriptionLength: "medium",
    tagStrategy: "species-tagged",
    commentResponseTone: "educational-warm",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  cars: {
    preferredUploadTime: "13:00-17:00",
    thumbnailStyle: "dramatic-angle",
    descriptionLength: "medium",
    tagStrategy: "make-model-tagged",
    commentResponseTone: "passionate",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-per-week",
  },
  automotive: {
    preferredUploadTime: "13:00-17:00",
    thumbnailStyle: "dramatic-angle",
    descriptionLength: "long",
    tagStrategy: "make-model-tagged",
    commentResponseTone: "knowledgeable",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-per-week",
  },
  science: {
    preferredUploadTime: "08:00-12:00",
    thumbnailStyle: "curiosity-sparking",
    descriptionLength: "long",
    tagStrategy: "question-driven",
    commentResponseTone: "curious-informative",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "weekly",
  },
  history: {
    preferredUploadTime: "08:00-12:00",
    thumbnailStyle: "dramatic-historical",
    descriptionLength: "long",
    tagStrategy: "era-event-tagged",
    commentResponseTone: "scholarly",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "weekly",
  },
  news: {
    preferredUploadTime: "06:00-10:00",
    thumbnailStyle: "headline-bold",
    descriptionLength: "medium",
    tagStrategy: "breaking-trending",
    commentResponseTone: "neutral-factual",
    crossPostPlatforms: ["x"],
    contentCadence: "daily",
  },
  commentary: {
    preferredUploadTime: "12:00-16:00",
    thumbnailStyle: "reaction-text-overlay",
    descriptionLength: "medium",
    tagStrategy: "topic-driven",
    commentResponseTone: "opinionated",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "3-per-week",
  },
  reaction: {
    preferredUploadTime: "14:00-18:00",
    thumbnailStyle: "expressive-split-screen",
    descriptionLength: "short",
    tagStrategy: "trending-content",
    commentResponseTone: "relatable",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "daily",
  },
  podcast: {
    preferredUploadTime: "06:00-10:00",
    thumbnailStyle: "guest-featured",
    descriptionLength: "long",
    tagStrategy: "guest-topic-tagged",
    commentResponseTone: "conversational",
    crossPostPlatforms: ["x", "tiktok"],
    contentCadence: "weekly",
  },
  animation: {
    preferredUploadTime: "12:00-16:00",
    thumbnailStyle: "vibrant-illustrated",
    descriptionLength: "medium",
    tagStrategy: "style-tagged",
    commentResponseTone: "creative",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "bi-weekly",
  },
  film: {
    preferredUploadTime: "16:00-20:00",
    thumbnailStyle: "cinematic-widescreen",
    descriptionLength: "long",
    tagStrategy: "title-genre-tagged",
    commentResponseTone: "analytical",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "weekly",
  },
  photography: {
    preferredUploadTime: "09:00-13:00",
    thumbnailStyle: "showcase-composition",
    descriptionLength: "medium",
    tagStrategy: "gear-technique-tagged",
    commentResponseTone: "artistic",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-per-week",
  },
  art: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "finished-piece-showcase",
    descriptionLength: "medium",
    tagStrategy: "medium-style-tagged",
    commentResponseTone: "creative-supportive",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-per-week",
  },
  design: {
    preferredUploadTime: "09:00-13:00",
    thumbnailStyle: "clean-portfolio",
    descriptionLength: "medium",
    tagStrategy: "tool-style-tagged",
    commentResponseTone: "professional-creative",
    crossPostPlatforms: ["x", "tiktok"],
    contentCadence: "2-per-week",
  },
  motivation: {
    preferredUploadTime: "05:00-09:00",
    thumbnailStyle: "bold-text-overlay",
    descriptionLength: "medium",
    tagStrategy: "emotion-driven",
    commentResponseTone: "inspiring",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "daily",
  },
  selfimprovement: {
    preferredUploadTime: "06:00-10:00",
    thumbnailStyle: "clean-aspirational",
    descriptionLength: "long",
    tagStrategy: "topic-habit-tagged",
    commentResponseTone: "empathetic",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  meditation: {
    preferredUploadTime: "05:00-08:00",
    thumbnailStyle: "calm-minimal",
    descriptionLength: "medium",
    tagStrategy: "wellness-tagged",
    commentResponseTone: "peaceful",
    crossPostPlatforms: ["tiktok"],
    contentCadence: "3-per-week",
  },
  yoga: {
    preferredUploadTime: "06:00-09:00",
    thumbnailStyle: "serene-pose",
    descriptionLength: "medium",
    tagStrategy: "practice-level-tagged",
    commentResponseTone: "calming",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "3-per-week",
  },
  health: {
    preferredUploadTime: "07:00-11:00",
    thumbnailStyle: "clean-medical",
    descriptionLength: "long",
    tagStrategy: "condition-tagged",
    commentResponseTone: "caring-informative",
    crossPostPlatforms: ["x", "tiktok"],
    contentCadence: "2-per-week",
  },
  parenting: {
    preferredUploadTime: "09:00-13:00",
    thumbnailStyle: "family-candid",
    descriptionLength: "medium",
    tagStrategy: "age-stage-tagged",
    commentResponseTone: "supportive-relatable",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  family: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "wholesome-candid",
    descriptionLength: "medium",
    tagStrategy: "family-activity-tagged",
    commentResponseTone: "warm-relatable",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  garden: {
    preferredUploadTime: "08:00-12:00",
    thumbnailStyle: "lush-green-close-up",
    descriptionLength: "long",
    tagStrategy: "plant-season-tagged",
    commentResponseTone: "nurturing",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-per-week",
  },
  homeimprovement: {
    preferredUploadTime: "09:00-13:00",
    thumbnailStyle: "before-after-split",
    descriptionLength: "long",
    tagStrategy: "project-material-tagged",
    commentResponseTone: "helpful-practical",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "weekly",
  },
  realestate: {
    preferredUploadTime: "08:00-12:00",
    thumbnailStyle: "property-showcase",
    descriptionLength: "long",
    tagStrategy: "location-price-tagged",
    commentResponseTone: "professional",
    crossPostPlatforms: ["x", "tiktok"],
    contentCadence: "3-per-week",
  },
  entrepreneurship: {
    preferredUploadTime: "07:00-11:00",
    thumbnailStyle: "bold-revenue-numbers",
    descriptionLength: "long",
    tagStrategy: "business-model-tagged",
    commentResponseTone: "mentor-like",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "2-3-per-week",
  },
  marketing: {
    preferredUploadTime: "08:00-12:00",
    thumbnailStyle: "case-study-clean",
    descriptionLength: "long",
    tagStrategy: "strategy-tagged",
    commentResponseTone: "strategic",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "2-per-week",
  },
  productivity: {
    preferredUploadTime: "06:00-10:00",
    thumbnailStyle: "minimal-organized",
    descriptionLength: "medium",
    tagStrategy: "tool-method-tagged",
    commentResponseTone: "efficient-helpful",
    crossPostPlatforms: ["x", "tiktok"],
    contentCadence: "2-per-week",
  },
  programming: {
    preferredUploadTime: "09:00-13:00",
    thumbnailStyle: "code-screenshot-clean",
    descriptionLength: "long",
    tagStrategy: "language-framework-tagged",
    commentResponseTone: "technical-friendly",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "2-per-week",
  },
  webdev: {
    preferredUploadTime: "09:00-13:00",
    thumbnailStyle: "website-preview",
    descriptionLength: "long",
    tagStrategy: "framework-tagged",
    commentResponseTone: "developer-friendly",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "2-3-per-week",
  },
  gamedev: {
    preferredUploadTime: "12:00-16:00",
    thumbnailStyle: "dev-log-progress",
    descriptionLength: "medium",
    tagStrategy: "engine-genre-tagged",
    commentResponseTone: "creative-technical",
    crossPostPlatforms: ["x", "discord", "tiktok"],
    contentCadence: "weekly",
  },
  datascience: {
    preferredUploadTime: "08:00-12:00",
    thumbnailStyle: "visualization-chart",
    descriptionLength: "long",
    tagStrategy: "tool-dataset-tagged",
    commentResponseTone: "analytical",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "weekly",
  },
  ai: {
    preferredUploadTime: "09:00-13:00",
    thumbnailStyle: "futuristic-clean",
    descriptionLength: "long",
    tagStrategy: "model-tool-tagged",
    commentResponseTone: "forward-thinking",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "2-3-per-week",
  },
  true_crime: {
    preferredUploadTime: "18:00-22:00",
    thumbnailStyle: "dark-mysterious",
    descriptionLength: "long",
    tagStrategy: "case-tagged",
    commentResponseTone: "empathetic-serious",
    crossPostPlatforms: ["x", "tiktok"],
    contentCadence: "weekly",
  },
  horror: {
    preferredUploadTime: "20:00-00:00",
    thumbnailStyle: "dark-suspenseful",
    descriptionLength: "medium",
    tagStrategy: "genre-mood-tagged",
    commentResponseTone: "mysterious",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "weekly",
  },
  paranormal: {
    preferredUploadTime: "20:00-00:00",
    thumbnailStyle: "eerie-atmospheric",
    descriptionLength: "long",
    tagStrategy: "location-event-tagged",
    commentResponseTone: "open-minded",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "weekly",
  },
  outdoors: {
    preferredUploadTime: "07:00-11:00",
    thumbnailStyle: "scenic-adventure",
    descriptionLength: "medium",
    tagStrategy: "activity-location-tagged",
    commentResponseTone: "adventurous",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "weekly",
  },
  fishing: {
    preferredUploadTime: "06:00-10:00",
    thumbnailStyle: "catch-reveal",
    descriptionLength: "medium",
    tagStrategy: "species-location-tagged",
    commentResponseTone: "patient-friendly",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-per-week",
  },
  hunting: {
    preferredUploadTime: "06:00-10:00",
    thumbnailStyle: "wilderness-action",
    descriptionLength: "medium",
    tagStrategy: "season-species-tagged",
    commentResponseTone: "respectful-experienced",
    crossPostPlatforms: ["x"],
    contentCadence: "weekly",
  },
  camping: {
    preferredUploadTime: "08:00-12:00",
    thumbnailStyle: "scenic-campsite",
    descriptionLength: "medium",
    tagStrategy: "gear-location-tagged",
    commentResponseTone: "outdoorsy-friendly",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "weekly",
  },
  survival: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "rugged-dramatic",
    descriptionLength: "long",
    tagStrategy: "skill-scenario-tagged",
    commentResponseTone: "authoritative",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "weekly",
  },
  miniatures: {
    preferredUploadTime: "12:00-16:00",
    thumbnailStyle: "detailed-macro",
    descriptionLength: "medium",
    tagStrategy: "hobby-material-tagged",
    commentResponseTone: "enthusiastic",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "weekly",
  },
  lego: {
    preferredUploadTime: "12:00-16:00",
    thumbnailStyle: "colorful-build",
    descriptionLength: "medium",
    tagStrategy: "set-theme-tagged",
    commentResponseTone: "fun-enthusiastic",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-per-week",
  },
  toys: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "bright-playful",
    descriptionLength: "medium",
    tagStrategy: "brand-age-tagged",
    commentResponseTone: "fun",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "3-per-week",
  },
  collectibles: {
    preferredUploadTime: "12:00-16:00",
    thumbnailStyle: "showcase-dramatic",
    descriptionLength: "medium",
    tagStrategy: "rarity-brand-tagged",
    commentResponseTone: "knowledgeable",
    crossPostPlatforms: ["x", "tiktok"],
    contentCadence: "2-per-week",
  },
  sneakers: {
    preferredUploadTime: "11:00-15:00",
    thumbnailStyle: "product-hero",
    descriptionLength: "medium",
    tagStrategy: "brand-model-tagged",
    commentResponseTone: "hype-knowledgeable",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "3-per-week",
  },
  watches: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "macro-luxury",
    descriptionLength: "long",
    tagStrategy: "brand-reference-tagged",
    commentResponseTone: "refined",
    crossPostPlatforms: ["x", "tiktok"],
    contentCadence: "2-per-week",
  },
  luxury: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "premium-editorial",
    descriptionLength: "medium",
    tagStrategy: "brand-lifestyle-tagged",
    commentResponseTone: "refined-aspirational",
    crossPostPlatforms: ["x", "tiktok"],
    contentCadence: "2-per-week",
  },
  cleaning: {
    preferredUploadTime: "09:00-13:00",
    thumbnailStyle: "satisfying-before-after",
    descriptionLength: "medium",
    tagStrategy: "method-product-tagged",
    commentResponseTone: "helpful-satisfying",
    crossPostPlatforms: ["tiktok"],
    contentCadence: "3-per-week",
  },
  organizing: {
    preferredUploadTime: "09:00-13:00",
    thumbnailStyle: "transformation-reveal",
    descriptionLength: "medium",
    tagStrategy: "space-method-tagged",
    commentResponseTone: "calm-helpful",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-per-week",
  },
  autos_racing: {
    preferredUploadTime: "14:00-18:00",
    thumbnailStyle: "speed-action",
    descriptionLength: "medium",
    tagStrategy: "event-team-tagged",
    commentResponseTone: "excited",
    crossPostPlatforms: ["x", "tiktok"],
    contentCadence: "2-3-per-week",
  },
  mma: {
    preferredUploadTime: "15:00-19:00",
    thumbnailStyle: "fight-action",
    descriptionLength: "medium",
    tagStrategy: "fighter-event-tagged",
    commentResponseTone: "passionate-analytical",
    crossPostPlatforms: ["x", "tiktok"],
    contentCadence: "3-per-week",
  },
  basketball: {
    preferredUploadTime: "15:00-19:00",
    thumbnailStyle: "highlight-action",
    descriptionLength: "medium",
    tagStrategy: "player-team-tagged",
    commentResponseTone: "energetic",
    crossPostPlatforms: ["x", "tiktok"],
    contentCadence: "3-5-per-week",
  },
  football: {
    preferredUploadTime: "15:00-19:00",
    thumbnailStyle: "highlight-action",
    descriptionLength: "medium",
    tagStrategy: "team-season-tagged",
    commentResponseTone: "energetic-analytical",
    crossPostPlatforms: ["x", "tiktok"],
    contentCadence: "3-per-week",
  },
  soccer: {
    preferredUploadTime: "14:00-18:00",
    thumbnailStyle: "match-highlight",
    descriptionLength: "medium",
    tagStrategy: "club-league-tagged",
    commentResponseTone: "passionate",
    crossPostPlatforms: ["x", "tiktok"],
    contentCadence: "3-per-week",
  },
  esports: {
    preferredUploadTime: "16:00-20:00",
    thumbnailStyle: "tournament-highlight",
    descriptionLength: "medium",
    tagStrategy: "game-team-tagged",
    commentResponseTone: "competitive-analytical",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "daily",
  },
  chess: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "board-position",
    descriptionLength: "long",
    tagStrategy: "opening-player-tagged",
    commentResponseTone: "intellectual",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "3-per-week",
  },
  tabletop: {
    preferredUploadTime: "14:00-18:00",
    thumbnailStyle: "game-setup-overhead",
    descriptionLength: "long",
    tagStrategy: "game-genre-tagged",
    commentResponseTone: "community-focused",
    crossPostPlatforms: ["discord", "x"],
    contentCadence: "weekly",
  },
  cardgames: {
    preferredUploadTime: "14:00-18:00",
    thumbnailStyle: "card-showcase",
    descriptionLength: "medium",
    tagStrategy: "set-deck-tagged",
    commentResponseTone: "strategic",
    crossPostPlatforms: ["tiktok", "x", "discord"],
    contentCadence: "2-3-per-week",
  },
  dance: {
    preferredUploadTime: "14:00-18:00",
    thumbnailStyle: "dynamic-movement",
    descriptionLength: "short",
    tagStrategy: "style-song-tagged",
    commentResponseTone: "energetic-encouraging",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "3-5-per-week",
  },
  singing: {
    preferredUploadTime: "16:00-20:00",
    thumbnailStyle: "performance-spotlight",
    descriptionLength: "short",
    tagStrategy: "song-genre-tagged",
    commentResponseTone: "appreciative",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  piano: {
    preferredUploadTime: "16:00-20:00",
    thumbnailStyle: "overhead-keys",
    descriptionLength: "short",
    tagStrategy: "piece-composer-tagged",
    commentResponseTone: "appreciative-educational",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  guitar: {
    preferredUploadTime: "16:00-20:00",
    thumbnailStyle: "close-up-playing",
    descriptionLength: "medium",
    tagStrategy: "song-technique-tagged",
    commentResponseTone: "jam-friendly",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  djing: {
    preferredUploadTime: "18:00-22:00",
    thumbnailStyle: "deck-performance",
    descriptionLength: "short",
    tagStrategy: "genre-set-tagged",
    commentResponseTone: "vibe-curator",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-per-week",
  },
  storytime: {
    preferredUploadTime: "12:00-16:00",
    thumbnailStyle: "expressive-text-hook",
    descriptionLength: "medium",
    tagStrategy: "topic-hook-tagged",
    commentResponseTone: "relatable-personal",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  books: {
    preferredUploadTime: "08:00-12:00",
    thumbnailStyle: "book-cover-aesthetic",
    descriptionLength: "long",
    tagStrategy: "genre-author-tagged",
    commentResponseTone: "thoughtful",
    crossPostPlatforms: ["x", "tiktok"],
    contentCadence: "2-per-week",
  },
  movies: {
    preferredUploadTime: "16:00-20:00",
    thumbnailStyle: "cinematic-still",
    descriptionLength: "long",
    tagStrategy: "title-genre-tagged",
    commentResponseTone: "analytical-passionate",
    crossPostPlatforms: ["x", "tiktok"],
    contentCadence: "2-per-week",
  },
  anime: {
    preferredUploadTime: "16:00-20:00",
    thumbnailStyle: "vibrant-key-visual",
    descriptionLength: "medium",
    tagStrategy: "series-genre-tagged",
    commentResponseTone: "passionate",
    crossPostPlatforms: ["x", "tiktok", "discord"],
    contentCadence: "2-3-per-week",
  },
  manga: {
    preferredUploadTime: "14:00-18:00",
    thumbnailStyle: "panel-showcase",
    descriptionLength: "medium",
    tagStrategy: "title-chapter-tagged",
    commentResponseTone: "fan-analytical",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "2-per-week",
  },
  cosplay: {
    preferredUploadTime: "12:00-16:00",
    thumbnailStyle: "character-reveal",
    descriptionLength: "medium",
    tagStrategy: "character-series-tagged",
    commentResponseTone: "creative-community",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "weekly",
  },
  spiritual: {
    preferredUploadTime: "06:00-10:00",
    thumbnailStyle: "ethereal-calm",
    descriptionLength: "long",
    tagStrategy: "practice-topic-tagged",
    commentResponseTone: "compassionate",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  astrology: {
    preferredUploadTime: "08:00-12:00",
    thumbnailStyle: "celestial-graphic",
    descriptionLength: "medium",
    tagStrategy: "sign-event-tagged",
    commentResponseTone: "mystical-personal",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "3-5-per-week",
  },
  politics: {
    preferredUploadTime: "07:00-11:00",
    thumbnailStyle: "headline-contrast",
    descriptionLength: "long",
    tagStrategy: "issue-event-tagged",
    commentResponseTone: "measured-factual",
    crossPostPlatforms: ["x"],
    contentCadence: "daily",
  },
  military: {
    preferredUploadTime: "08:00-12:00",
    thumbnailStyle: "dramatic-documentary",
    descriptionLength: "long",
    tagStrategy: "topic-era-tagged",
    commentResponseTone: "respectful-informative",
    crossPostPlatforms: ["x"],
    contentCadence: "weekly",
  },
  space: {
    preferredUploadTime: "09:00-13:00",
    thumbnailStyle: "cosmic-awe",
    descriptionLength: "long",
    tagStrategy: "mission-discovery-tagged",
    commentResponseTone: "wonder-driven",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "2-per-week",
  },
  math: {
    preferredUploadTime: "08:00-12:00",
    thumbnailStyle: "equation-visual",
    descriptionLength: "long",
    tagStrategy: "topic-level-tagged",
    commentResponseTone: "patient-educational",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "2-per-week",
  },
  language: {
    preferredUploadTime: "08:00-12:00",
    thumbnailStyle: "bilingual-text",
    descriptionLength: "medium",
    tagStrategy: "language-level-tagged",
    commentResponseTone: "encouraging-educational",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "daily",
  },
  prepping: {
    preferredUploadTime: "09:00-13:00",
    thumbnailStyle: "gear-stockpile",
    descriptionLength: "long",
    tagStrategy: "scenario-gear-tagged",
    commentResponseTone: "practical-serious",
    crossPostPlatforms: ["x"],
    contentCadence: "weekly",
  },
  woodworking: {
    preferredUploadTime: "09:00-13:00",
    thumbnailStyle: "finished-piece-detail",
    descriptionLength: "long",
    tagStrategy: "project-tool-tagged",
    commentResponseTone: "craftsman-helpful",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "weekly",
  },
  metalwork: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "forge-action",
    descriptionLength: "medium",
    tagStrategy: "technique-material-tagged",
    commentResponseTone: "craftsman-proud",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "weekly",
  },
  thrifting: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "treasure-find",
    descriptionLength: "medium",
    tagStrategy: "find-price-tagged",
    commentResponseTone: "excited-thrifty",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  reselling: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "profit-reveal",
    descriptionLength: "medium",
    tagStrategy: "platform-profit-tagged",
    commentResponseTone: "business-savvy",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  unboxing: {
    preferredUploadTime: "12:00-16:00",
    thumbnailStyle: "mystery-reveal",
    descriptionLength: "medium",
    tagStrategy: "brand-product-tagged",
    commentResponseTone: "excited",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "3-per-week",
  },
  mukbang: {
    preferredUploadTime: "12:00-16:00",
    thumbnailStyle: "food-feast-close-up",
    descriptionLength: "short",
    tagStrategy: "food-type-tagged",
    commentResponseTone: "fun-interactive",
    crossPostPlatforms: ["tiktok"],
    contentCadence: "3-5-per-week",
  },
  baking: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "finished-bake-close-up",
    descriptionLength: "long",
    tagStrategy: "recipe-type-tagged",
    commentResponseTone: "warm-encouraging",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-per-week",
  },
  cocktails: {
    preferredUploadTime: "17:00-21:00",
    thumbnailStyle: "elegant-drink-shot",
    descriptionLength: "medium",
    tagStrategy: "drink-spirit-tagged",
    commentResponseTone: "sophisticated-fun",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  wine: {
    preferredUploadTime: "17:00-21:00",
    thumbnailStyle: "elegant-pour",
    descriptionLength: "long",
    tagStrategy: "region-varietal-tagged",
    commentResponseTone: "refined-educational",
    crossPostPlatforms: ["x", "tiktok"],
    contentCadence: "2-per-week",
  },
  coffee: {
    preferredUploadTime: "06:00-10:00",
    thumbnailStyle: "artisan-pour",
    descriptionLength: "medium",
    tagStrategy: "method-origin-tagged",
    commentResponseTone: "connoisseur-friendly",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  skincare: {
    preferredUploadTime: "09:00-13:00",
    thumbnailStyle: "clean-product-glow",
    descriptionLength: "long",
    tagStrategy: "ingredient-concern-tagged",
    commentResponseTone: "caring-knowledgeable",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  nails: {
    preferredUploadTime: "11:00-15:00",
    thumbnailStyle: "macro-nail-art",
    descriptionLength: "medium",
    tagStrategy: "style-product-tagged",
    commentResponseTone: "creative-supportive",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  hair: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "transformation-reveal",
    descriptionLength: "medium",
    tagStrategy: "style-technique-tagged",
    commentResponseTone: "encouraging",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-per-week",
  },
  tattoo: {
    preferredUploadTime: "12:00-16:00",
    thumbnailStyle: "finished-piece-detail",
    descriptionLength: "medium",
    tagStrategy: "style-placement-tagged",
    commentResponseTone: "artistic-respectful",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-per-week",
  },
  pranks: {
    preferredUploadTime: "14:00-18:00",
    thumbnailStyle: "reaction-freeze-frame",
    descriptionLength: "short",
    tagStrategy: "viral-hook-tagged",
    commentResponseTone: "playful",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  challenges: {
    preferredUploadTime: "14:00-18:00",
    thumbnailStyle: "dramatic-attempt",
    descriptionLength: "short",
    tagStrategy: "trending-challenge-tagged",
    commentResponseTone: "fun-engaging",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "3-per-week",
  },
  magic: {
    preferredUploadTime: "14:00-18:00",
    thumbnailStyle: "impossible-moment",
    descriptionLength: "short",
    tagStrategy: "trick-type-tagged",
    commentResponseTone: "mysterious-showman",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  drone: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "aerial-cinematic",
    descriptionLength: "medium",
    tagStrategy: "location-gear-tagged",
    commentResponseTone: "enthusiast",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "weekly",
  },
  "3dprinting": {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "print-result-showcase",
    descriptionLength: "long",
    tagStrategy: "printer-material-tagged",
    commentResponseTone: "maker-helpful",
    crossPostPlatforms: ["tiktok", "x", "discord"],
    contentCadence: "2-per-week",
  },
  electronics: {
    preferredUploadTime: "09:00-13:00",
    thumbnailStyle: "circuit-close-up",
    descriptionLength: "long",
    tagStrategy: "component-project-tagged",
    commentResponseTone: "technical-patient",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "weekly",
  },
  robotics: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "robot-action-demo",
    descriptionLength: "long",
    tagStrategy: "project-tech-tagged",
    commentResponseTone: "engineering-enthusiast",
    crossPostPlatforms: ["x", "discord", "tiktok"],
    contentCadence: "bi-weekly",
  },
  law: {
    preferredUploadTime: "08:00-12:00",
    thumbnailStyle: "authority-clean",
    descriptionLength: "long",
    tagStrategy: "topic-case-tagged",
    commentResponseTone: "authoritative-accessible",
    crossPostPlatforms: ["x", "tiktok"],
    contentCadence: "2-per-week",
  },
  medical: {
    preferredUploadTime: "07:00-11:00",
    thumbnailStyle: "clinical-clean",
    descriptionLength: "long",
    tagStrategy: "condition-specialty-tagged",
    commentResponseTone: "professional-empathetic",
    crossPostPlatforms: ["x", "tiktok"],
    contentCadence: "2-per-week",
  },
  psychology: {
    preferredUploadTime: "08:00-12:00",
    thumbnailStyle: "thought-provoking",
    descriptionLength: "long",
    tagStrategy: "concept-study-tagged",
    commentResponseTone: "empathetic-analytical",
    crossPostPlatforms: ["x", "tiktok"],
    contentCadence: "2-per-week",
  },
  philosophy: {
    preferredUploadTime: "08:00-12:00",
    thumbnailStyle: "minimalist-profound",
    descriptionLength: "long",
    tagStrategy: "thinker-concept-tagged",
    commentResponseTone: "reflective",
    crossPostPlatforms: ["x"],
    contentCadence: "weekly",
  },
  relationships: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "emotive-text-overlay",
    descriptionLength: "medium",
    tagStrategy: "topic-advice-tagged",
    commentResponseTone: "empathetic-honest",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  wedding: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "elegant-romantic",
    descriptionLength: "long",
    tagStrategy: "vendor-style-tagged",
    commentResponseTone: "celebratory",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-per-week",
  },
  vanlife: {
    preferredUploadTime: "08:00-12:00",
    thumbnailStyle: "scenic-van-adventure",
    descriptionLength: "medium",
    tagStrategy: "location-lifestyle-tagged",
    commentResponseTone: "free-spirited",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  homestead: {
    preferredUploadTime: "07:00-11:00",
    thumbnailStyle: "rustic-authentic",
    descriptionLength: "long",
    tagStrategy: "skill-season-tagged",
    commentResponseTone: "self-sufficient",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-per-week",
  },
  farming: {
    preferredUploadTime: "06:00-10:00",
    thumbnailStyle: "field-harvest",
    descriptionLength: "medium",
    tagStrategy: "crop-season-tagged",
    commentResponseTone: "down-to-earth",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  aquarium: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "underwater-vibrant",
    descriptionLength: "long",
    tagStrategy: "species-tank-tagged",
    commentResponseTone: "hobbyist-helpful",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "weekly",
  },
  rc: {
    preferredUploadTime: "12:00-16:00",
    thumbnailStyle: "action-terrain",
    descriptionLength: "medium",
    tagStrategy: "model-brand-tagged",
    commentResponseTone: "enthusiast",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "weekly",
  },
  knitting: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "cozy-finished-piece",
    descriptionLength: "long",
    tagStrategy: "pattern-yarn-tagged",
    commentResponseTone: "warm-patient",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "weekly",
  },
  sewing: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "transformation-garment",
    descriptionLength: "long",
    tagStrategy: "pattern-fabric-tagged",
    commentResponseTone: "crafty-helpful",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "weekly",
  },
  pottery: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "wheel-throwing-satisfying",
    descriptionLength: "medium",
    tagStrategy: "technique-glaze-tagged",
    commentResponseTone: "zen-creative",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-per-week",
  },
  calligraphy: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "elegant-stroke-close-up",
    descriptionLength: "short",
    tagStrategy: "style-tool-tagged",
    commentResponseTone: "artistic-meditative",
    crossPostPlatforms: ["tiktok", "x"],
    contentCadence: "2-3-per-week",
  },
  default: {
    preferredUploadTime: "10:00-14:00",
    thumbnailStyle: "eye-catching",
    descriptionLength: "medium",
    tagStrategy: "balanced",
    commentResponseTone: "friendly",
    crossPostPlatforms: ["x", "discord"],
    contentCadence: "2-3-per-week",
  },
};

export async function autoOptimizeSettings(userId: string): Promise<OptimizationResult> {
  const lastRun = lastOptimized.get(userId);
  if (lastRun && Date.now() - lastRun < OPTIMIZE_COOLDOWN_MS) {
    return { optimized: false, summary: "Recently optimized, skipping", changes: [] };
  }

  const changes: string[] = [];

  try {
    const user = await storage.getUser(userId);
    if (!user) return { optimized: false, summary: "User not found", changes: [] };

    const niche = (user.contentNiche || "default").toLowerCase();
    const optimalSettings = NICHE_OPTIMAL_SETTINGS[niche] || NICHE_OPTIMAL_SETTINGS.default;

    const userVideos = await storage.getVideosByUser(userId);
    const userChannels = await storage.getChannelsByUser(userId);

    if (!user.autopilotActive && userChannels.length > 0 && userVideos.length > 0) {
      await storage.updateUserProfile(userId, { autopilotActive: true });
      changes.push("Auto-enabled autopilot (channels connected with content ready)");
    }

    if (!user.contentNiche && userVideos.length > 0) {
      const videoTitles = userVideos.slice(0, 10).map(v => v.title).join(", ");
      const inferredNiche = inferNicheFromContent(videoTitles);
      if (inferredNiche) {
        await storage.updateUserProfile(userId, { contentNiche: inferredNiche });
        changes.push(`Auto-detected content niche: ${inferredNiche}`);
      }
    }

    if (!user.notifyEmail && user.email) {
      await storage.updateUserProfile(userId, { notifyEmail: true });
      changes.push("Auto-enabled email notifications for exception alerts");
    }

    lastOptimized.set(userId, Date.now());

    return {
      optimized: changes.length > 0,
      summary: changes.length > 0
        ? `Optimized ${changes.length} settings: ${changes.join("; ")}`
        : "All settings already optimal",
      changes,
    };
  } catch (err) {
    console.error(`[AutoSettings] Optimization error for ${userId}:`, err);
    return { optimized: false, summary: "Optimization error", changes: [] };
  }
}

function inferNicheFromContent(titles: string): string | null {
  const lower = titles.toLowerCase();
  const nicheKeywords: Record<string, string[]> = {
    gaming: ["game", "play", "stream", "fps", "rpg", "minecraft", "fortnite", "valorant", "cod", "gta", "gaming", "xbox", "playstation", "nintendo", "twitch"],
    tech: ["review", "unbox", "setup", "tech", "gadget", "software", "app", "device", "specs", "benchmark"],
    vlog: ["day in", "life", "vlog", "routine", "grwm", "haul", "my morning", "come with me", "a day"],
    education: ["learn", "how to", "explained", "course", "lesson", "tutorial", "guide", "tips", "lecture"],
    music: ["song", "cover", "beat", "music", "remix", "producer", "album", "track", "melody", "lyrics"],
    fitness: ["workout", "exercise", "gym", "fitness", "gains", "bodybuilding", "training", "diet", "reps", "cardio"],
    cooking: ["recipe", "cook", "food", "kitchen", "meal", "chef", "ingredients", "dinner", "lunch", "sauce"],
    beauty: ["makeup", "beauty", "cosmetic", "foundation", "lipstick", "eyeshadow", "concealer", "contour", "glam"],
    fashion: ["fashion", "outfit", "style", "ootd", "wardrobe", "trend", "lookbook", "clothing", "dress"],
    travel: ["travel", "destination", "flight", "hotel", "backpack", "passport", "explore", "vacation", "trip"],
    comedy: ["comedy", "funny", "skit", "joke", "hilarious", "laugh", "parody", "standup", "meme"],
    sports: ["sport", "match", "game day", "goal", "score", "playoffs", "championship", "athlete", "league"],
    finance: ["invest", "stock", "money", "finance", "budget", "portfolio", "dividend", "wealth", "savings", "retire"],
    crypto: ["crypto", "bitcoin", "ethereum", "blockchain", "token", "defi", "nft", "altcoin", "wallet", "mining"],
    asmr: ["asmr", "tingle", "whisper", "relaxing", "triggers", "sleep", "calming", "soft spoken"],
    diy: ["diy", "do it yourself", "homemade", "handmade", "hack", "project", "renovation", "restore"],
    crafts: ["craft", "crochet", "scrapbook", "paper", "resin", "macrame", "embroidery", "handcraft"],
    pets: ["pet", "dog", "cat", "puppy", "kitten", "parrot", "hamster", "bunny", "ferret", "adopted"],
    animals: ["animal", "wildlife", "nature", "safari", "zoo", "marine", "bird", "reptile", "insect"],
    cars: ["car", "supercar", "horsepower", "engine", "turbo", "drift", "exhaust", "modification", "tuning"],
    automotive: ["automotive", "mechanic", "repair", "garage", "oil change", "brake", "transmission", "diagnostic"],
    science: ["science", "experiment", "physics", "chemistry", "biology", "research", "discovery", "lab"],
    history: ["history", "ancient", "medieval", "empire", "war", "civilization", "historical", "century", "dynasty"],
    news: ["news", "breaking", "headline", "report", "update", "current events", "press", "journalist"],
    commentary: ["commentary", "opinion", "analysis", "take", "rant", "discussion", "hot take", "react"],
    reaction: ["reaction", "reacting", "first time", "watching", "responding", "react to"],
    podcast: ["podcast", "episode", "interview", "guest", "host", "conversation", "ep.", "pod"],
    animation: ["animation", "animate", "cartoon", "2d", "3d animation", "motion graphics", "animated"],
    film: ["film", "movie", "cinema", "director", "screenplay", "short film", "indie film", "cinematography"],
    photography: ["photography", "photo", "portrait", "landscape", "camera", "lens", "lightroom", "aperture"],
    art: ["art", "drawing", "painting", "sketch", "illustration", "watercolor", "canvas", "acrylic", "digital art"],
    design: ["design", "graphic design", "ui", "ux", "logo", "branding", "figma", "photoshop", "illustrator"],
    motivation: ["motivation", "motivational", "grind", "hustle", "mindset", "discipline", "success", "inspire"],
    selfimprovement: ["self improvement", "self-improvement", "growth", "habits", "stoic", "productivity", "better", "mindful"],
    meditation: ["meditation", "meditate", "mindfulness", "breathing", "zen", "guided meditation", "peace"],
    yoga: ["yoga", "pose", "asana", "flexibility", "stretch", "flow", "vinyasa", "namaste"],
    health: ["health", "wellness", "nutrition", "supplement", "vitamin", "immune", "disease", "doctor"],
    parenting: ["parenting", "parent", "mom", "dad", "baby", "toddler", "kids", "newborn", "pregnancy"],
    family: ["family", "siblings", "home life", "family time", "family fun", "with my family"],
    garden: ["garden", "plant", "flower", "seed", "grow", "compost", "harvest", "greenhouse", "herb"],
    homeimprovement: ["home improvement", "renovation", "remodel", "interior", "bathroom", "flooring", "tile", "drywall"],
    realestate: ["real estate", "property", "house", "condo", "mortgage", "listing", "realtor", "home tour"],
    entrepreneurship: ["entrepreneur", "startup", "business", "founder", "revenue", "side hustle", "brand", "ceo"],
    marketing: ["marketing", "seo", "ads", "branding", "funnel", "email marketing", "social media marketing", "conversion"],
    productivity: ["productivity", "notion", "planner", "time management", "efficient", "workflow", "organize"],
    programming: ["programming", "code", "coding", "developer", "javascript", "python", "react", "api", "github"],
    webdev: ["web dev", "web development", "frontend", "backend", "html", "css", "tailwind", "nextjs", "website"],
    gamedev: ["game dev", "game development", "unity", "unreal", "godot", "indie game", "devlog", "pixel art"],
    datascience: ["data science", "machine learning", "dataset", "pandas", "tensorflow", "jupyter", "neural"],
    ai: ["artificial intelligence", "ai", "chatgpt", "openai", "llm", "generative", "prompt", "deep learning"],
    true_crime: ["true crime", "murder", "investigation", "case", "cold case", "serial killer", "mystery", "forensic"],
    horror: ["horror", "scary", "creepy", "haunted", "ghost", "nightmare", "terrifying", "paranormal activity"],
    paranormal: ["paranormal", "supernatural", "ufo", "bigfoot", "alien", "unexplained", "encounter"],
    outdoors: ["outdoor", "hiking", "trail", "mountain", "backpacking", "wilderness", "adventure", "summit"],
    fishing: ["fishing", "bass", "trout", "catch", "lure", "tackle", "angler", "reel", "rod"],
    hunting: ["hunting", "deer", "elk", "bow", "hunt", "rifle", "season", "buck", "camo"],
    camping: ["camping", "camp", "tent", "campfire", "campsite", "overlanding", "glamping"],
    survival: ["survival", "bushcraft", "survive", "shelter", "wilderness survival", "prepper", "off grid"],
    miniatures: ["miniature", "warhammer", "mini painting", "tabletop miniature", "scale model", "diorama"],
    lego: ["lego", "moc", "brick", "minifigure", "lego set", "lego build"],
    toys: ["toy", "action figure", "doll", "playset", "hot wheels", "nerf", "collectible toy"],
    collectibles: ["collection", "collectible", "rare", "vintage", "antique", "card collection", "coin"],
    sneakers: ["sneaker", "jordans", "nike", "adidas", "kicks", "shoe", "yeezy", "drop", "resell"],
    watches: ["watch", "rolex", "omega", "seiko", "horology", "timepiece", "wrist", "automatic"],
    luxury: ["luxury", "designer", "gucci", "louis vuitton", "hermes", "chanel", "premium", "high end"],
    cleaning: ["cleaning", "clean", "satisfying clean", "deep clean", "tidy", "organize", "declutter"],
    organizing: ["organizing", "organization", "storage", "pantry", "closet", "label", "container"],
    autos_racing: ["racing", "formula 1", "f1", "nascar", "rally", "track day", "drag race", "race car"],
    mma: ["mma", "ufc", "boxing", "fight", "martial arts", "knockout", "sparring", "jiu jitsu"],
    basketball: ["basketball", "nba", "dunk", "court", "layup", "three pointer", "hoops"],
    football: ["football", "nfl", "touchdown", "quarterback", "super bowl", "gridiron"],
    soccer: ["soccer", "premier league", "la liga", "champions league", "goal", "penalty", "match day"],
    esports: ["esports", "tournament", "competitive", "pro player", "league of legends", "csgo", "overwatch"],
    chess: ["chess", "checkmate", "opening", "grandmaster", "elo", "gambit", "endgame", "stockfish"],
    tabletop: ["tabletop", "board game", "dungeons", "d&d", "rpg session", "game night", "campaign"],
    cardgames: ["card game", "pokemon cards", "mtg", "magic the gathering", "yugioh", "trading card", "pack opening"],
    dance: ["dance", "choreography", "dancer", "routine", "hip hop dance", "ballet", "breakdance", "twerk"],
    singing: ["singing", "singer", "vocal", "voice", "karaoke", "sing", "performance", "acapella"],
    piano: ["piano", "pianist", "keys", "classical piano", "piano cover", "sheet music"],
    guitar: ["guitar", "guitarist", "acoustic", "electric guitar", "riff", "tab", "chord", "solo"],
    djing: ["dj", "djing", "mix", "set", "edm", "house music", "techno", "turntable", "beatdrop"],
    storytime: ["storytime", "story time", "what happened", "let me tell you", "my experience"],
    books: ["book", "reading", "novel", "author", "booktok", "bookshelf", "library", "literary", "chapter"],
    movies: ["movie review", "film review", "cinema", "box office", "trailer", "screenplay", "director"],
    anime: ["anime", "otaku", "waifu", "shonen", "seinen", "isekai", "manga anime", "sub", "dub"],
    manga: ["manga", "chapter", "panel", "mangaka", "shonen jump", "one piece", "naruto"],
    cosplay: ["cosplay", "cosplayer", "costume", "convention", "con", "character", "prop making"],
    spiritual: ["spiritual", "spirituality", "energy", "manifestation", "universe", "chakra", "healing"],
    astrology: ["astrology", "zodiac", "horoscope", "mercury retrograde", "birth chart", "tarot"],
    politics: ["politics", "political", "election", "congress", "senate", "policy", "government", "democrat", "republican"],
    military: ["military", "army", "navy", "air force", "veteran", "combat", "deployment", "service"],
    space: ["space", "nasa", "rocket", "astronaut", "planet", "telescope", "mars", "moon", "orbit"],
    math: ["math", "mathematics", "equation", "calculus", "algebra", "geometry", "theorem", "proof"],
    language: ["language", "learn spanish", "learn japanese", "learn french", "polyglot", "bilingual", "vocabulary"],
    prepping: ["prepping", "prepper", "emergency", "stockpile", "bug out", "shtf", "preparedness"],
    woodworking: ["woodworking", "woodwork", "lathe", "joinery", "sawdust", "plywood", "dovetail", "epoxy table"],
    metalwork: ["metalwork", "welding", "forge", "blacksmith", "anvil", "grinder", "fabrication"],
    thrifting: ["thrift", "thrifting", "goodwill", "second hand", "thrift store", "estate sale", "flea market"],
    reselling: ["resell", "reselling", "flip", "profit", "ebay", "poshmark", "mercari", "sourcing"],
    unboxing: ["unboxing", "unbox", "first look", "haul", "package", "mail day", "what i got"],
    mukbang: ["mukbang", "eating", "food challenge", "asmr eating", "eating show", "food review"],
    baking: ["bake", "baking", "cake", "pastry", "bread", "sourdough", "cookies", "cupcake", "frosting"],
    cocktails: ["cocktail", "mixology", "bartender", "drink", "spirits", "shaker", "martini", "margarita"],
    wine: ["wine", "winery", "vineyard", "sommelier", "tasting", "cabernet", "merlot", "chardonnay"],
    coffee: ["coffee", "espresso", "latte", "barista", "pour over", "french press", "cold brew", "roast"],
    skincare: ["skincare", "skin care", "moisturizer", "serum", "sunscreen", "retinol", "acne", "glow up"],
    nails: ["nails", "nail art", "manicure", "gel nails", "acrylic", "nail polish", "press on"],
    hair: ["hair", "hairstyle", "haircut", "hair color", "curly hair", "straight hair", "blowout", "balayage"],
    tattoo: ["tattoo", "ink", "tattoo artist", "sleeve", "tattoo design", "body art"],
    pranks: ["prank", "pranking", "got em", "epic prank", "scare prank", "public prank"],
    challenges: ["challenge", "24 hour", "last to leave", "try not to", "extreme", "impossible"],
    magic: ["magic trick", "illusion", "magician", "card trick", "sleight of hand", "disappear"],
    drone: ["drone", "fpv", "aerial", "drone footage", "quadcopter", "dji", "mavic"],
    "3dprinting": ["3d print", "3d printing", "stl", "filament", "printer", "resin print", "slicer"],
    electronics: ["electronics", "circuit", "arduino", "raspberry pi", "soldering", "pcb", "microcontroller"],
    robotics: ["robot", "robotics", "servo", "autonomous", "mechatronics", "prosthetic"],
    law: ["law", "lawyer", "legal", "court", "attorney", "lawsuit", "contract", "judge"],
    medical: ["medical", "medicine", "surgery", "hospital", "nurse", "diagnosis", "clinical"],
    psychology: ["psychology", "mental health", "therapy", "therapist", "cognitive", "behavior", "anxiety"],
    philosophy: ["philosophy", "philosopher", "existential", "ethics", "moral", "plato", "nietzsche"],
    relationships: ["relationship", "dating", "couple", "love", "breakup", "marriage", "partner"],
    wedding: ["wedding", "bride", "groom", "engagement", "bridal", "ceremony", "reception"],
    vanlife: ["vanlife", "van life", "van build", "camper van", "road trip", "nomad", "conversion"],
    homestead: ["homestead", "homesteading", "self sufficient", "off grid", "chickens", "livestock"],
    farming: ["farm", "farming", "tractor", "crop", "harvest", "barn", "agriculture", "ranch"],
    aquarium: ["aquarium", "fish tank", "reef", "aquascape", "betta", "cichlid", "planted tank"],
    rc: ["rc car", "rc plane", "remote control", "fpv racing", "rc boat", "scale rc"],
    knitting: ["knitting", "knit", "yarn", "needles", "pattern", "stitch", "cast on"],
    sewing: ["sewing", "sew", "fabric", "seam", "machine", "quilt", "hemming", "alterations"],
    pottery: ["pottery", "ceramics", "clay", "kiln", "glaze", "wheel throwing", "stoneware"],
    calligraphy: ["calligraphy", "lettering", "brush pen", "fountain pen", "hand lettering", "script"],
  };

  let bestNiche: string | null = null;
  let bestScore = 0;

  for (const [niche, keywords] of Object.entries(nicheKeywords)) {
    const score = keywords.filter(kw => lower.includes(kw)).length;
    if (score > bestScore) {
      bestScore = score;
      bestNiche = niche;
    }
  }

  return bestScore >= 2 ? bestNiche : null;
}

export async function getOptimalSettings(userId: string): Promise<Record<string, any>> {
  const user = await storage.getUser(userId);
  const niche = (user?.contentNiche || "default").toLowerCase();
  return NICHE_OPTIMAL_SETTINGS[niche] || NICHE_OPTIMAL_SETTINGS.default;
}
