/**
 * creative-library-manager.ts
 *
 * The ever-expanding creative asset library for ET Gaming 274.
 *
 * Every music track, video filter, title template, hook pattern, and editing
 * preset that has ever been generated or discovered lives here.  Assets are
 * scored by real YouTube Analytics (retention + CTR + success rate).  The
 * highest-scoring items are automatically preferred by the encoder and AI
 * systems — bad performers sink, good ones rise to the top over time.
 *
 * The library grows in two ways:
 *   1. Seeded on boot from existing files/presets (idempotent)
 *   2. New items are generated by the AI systems and added here
 *
 * Public API:
 *   seedMusicLibrary(channelId)       — seeds .mp3 files from music-library dir
 *   getBestItem(channelId, type, tag) — highest-scoring active item for a role
 *   addToLibrary(item)                — add a new item (deduplicates by filePath)
 *   recordUsage(itemId)               — increment usage counter (fire-and-forget)
 *   recordPerformance(id, ret, ctr)   — update score from YouTube Analytics
 *   listLibraryItems(channelId, type) — all items for the library UI
 *   setItemActive(id, active)         — soft-delete / restore
 */

import fs from "fs";
import path from "path";
import { and, desc, eq, sql } from "drizzle-orm";
import { db } from "../db";
import { creativeLibrary } from "@shared/schema";
import { createLogger } from "../lib/logger";

const logger = createLogger("creative-library");

export const MUSIC_LIBRARY_DIR = path.join(process.cwd(), "data", "music-library");

// ── Tag semantics for music tracks ───────────────────────────────────────────
// Each act in the narrative score assembly has a canonical tag.
// When new tracks are generated they must carry one of these tags so the
// music-scorer can find them via getBestItem().
const MUSIC_FILE_TAGS: Array<{ prefix: string; tags: string[] }> = [
  { prefix: "act1_intro",   tags: ["intro",     "longform"] },
  { prefix: "act2_rising",  tags: ["rising",    "longform"] },
  { prefix: "act3_climax",  tags: ["climax",    "longform"] },
  { prefix: "act4_falling", tags: ["falling",   "longform"] },
  { prefix: "act5_outro",   tags: ["outro",     "longform"] },
  { prefix: "short_arc",    tags: ["short_arc", "short"]   },
];

function tagsForFile(filename: string): string[] {
  const base = filename.replace(/\.mp3$/i, "");
  for (const { prefix, tags } of MUSIC_FILE_TAGS) {
    if (base.startsWith(prefix)) return tags;
  }
  return ["music"];
}

function humanName(filename: string): string {
  return filename
    .replace(/\.mp3$/i, "")
    .replace(/_(\d+)$/, " $1")
    .replace(/_/g, " ")
    .replace(/\b\w/g, c => c.toUpperCase());
}

// ── Seed existing music files ─────────────────────────────────────────────────

export async function seedMusicLibrary(channelId: number): Promise<void> {
  try {
    if (!fs.existsSync(MUSIC_LIBRARY_DIR)) return;

    const files = fs.readdirSync(MUSIC_LIBRARY_DIR)
      .filter(f => f.endsWith(".mp3") && fs.existsSync(path.join(MUSIC_LIBRARY_DIR, f)));

    let added = 0;
    for (const file of files) {
      const filePath = path.join(MUSIC_LIBRARY_DIR, file);
      const tags = tagsForFile(file);

      const existing = await db
        .select({ id: creativeLibrary.id })
        .from(creativeLibrary)
        .where(and(
          eq(creativeLibrary.channelId, channelId),
          eq(creativeLibrary.filePath, filePath),
        ))
        .limit(1);

      if (existing.length === 0) {
        await db.insert(creativeLibrary).values({
          channelId,
          type: "music",
          name: humanName(file),
          description: `AI-generated ${tags.includes("short") ? "Short" : "long-form"} music track — ${tags.filter(t => !["short", "longform"].includes(t)).join(", ")} role`,
          filePath,
          tags,
          source: "ai_generated",
        });
        added++;
      }
    }

    if (added > 0) {
      logger.info(`[CreativeLibrary] Seeded ${added} music track(s) for channel ${channelId}`);
    }
  } catch (err: any) {
    logger.warn(`[CreativeLibrary] Seed failed (non-fatal): ${err?.message}`);
  }
}

// ── Query: best item by type + role tag ──────────────────────────────────────

export async function getBestItem(
  channelId: number,
  type: string,
  tag: string,
): Promise<{ id: number; filePath: string | null; name: string } | null> {
  try {
    const rows = await db
      .select({ id: creativeLibrary.id, filePath: creativeLibrary.filePath, name: creativeLibrary.name })
      .from(creativeLibrary)
      .where(and(
        eq(creativeLibrary.channelId, channelId),
        eq(creativeLibrary.type, type),
        eq(creativeLibrary.active, true),
        sql`${creativeLibrary.tags} @> ARRAY[${tag}]::text[]`,
      ))
      .orderBy(desc(creativeLibrary.performanceScore), desc(creativeLibrary.usageCount))
      .limit(3); // pick from top 3 to add variety

    if (rows.length === 0) return null;
    // Weighted random among top performers so the library stays diverse
    return rows[Math.floor(Math.random() * rows.length)];
  } catch {
    return null;
  }
}

// ── Add new item (deduplicates by filePath) ───────────────────────────────────

export async function addToLibrary(item: {
  channelId: number;
  type: string;
  name: string;
  description?: string;
  filePath?: string;
  config?: Record<string, unknown>;
  tags: string[];
  source?: string;
  metadata?: Record<string, unknown>;
}): Promise<number | null> {
  try {
    if (item.filePath) {
      const existing = await db
        .select({ id: creativeLibrary.id })
        .from(creativeLibrary)
        .where(and(
          eq(creativeLibrary.channelId, item.channelId),
          eq(creativeLibrary.filePath, item.filePath),
        ))
        .limit(1);
      if (existing.length > 0) return existing[0].id;
    }

    const [row] = await db.insert(creativeLibrary).values({
      channelId: item.channelId,
      type:       item.type,
      name:       item.name,
      description: item.description,
      filePath:   item.filePath,
      config:     item.config ?? {},
      tags:       item.tags,
      source:     item.source ?? "ai_generated",
      metadata:   item.metadata ?? {},
    }).returning({ id: creativeLibrary.id });

    logger.info(`[CreativeLibrary] Added: "${item.name}" [${item.tags.join(", ")}]`);
    return row.id;
  } catch (err: any) {
    logger.warn(`[CreativeLibrary] addToLibrary failed: ${err?.message}`);
    return null;
  }
}

// ── Record usage (fire-and-forget) ────────────────────────────────────────────

export function recordUsage(itemId: number): void {
  db.update(creativeLibrary)
    .set({ usageCount: sql`${creativeLibrary.usageCount} + 1`, updatedAt: sql`now()` })
    .where(eq(creativeLibrary.id, itemId))
    .catch(() => {});
}

// ── Record performance from YouTube Analytics ─────────────────────────────────
// Called after a video gets analytics data and we know which library items
// were used in its production.  Updates the composite performance score.

export async function recordPerformance(
  itemId: number,
  retention: number, // 0–100 (average % of video watched)
  ctr: number,       // 0–100 (click-through rate %)
): Promise<void> {
  try {
    const [current] = await db
      .select({ usageCount: creativeLibrary.usageCount, successCount: creativeLibrary.successCount })
      .from(creativeLibrary)
      .where(eq(creativeLibrary.id, itemId))
      .limit(1);

    if (!current) return;

    const isSuccess = retention >= 35; // above-average viewer retention = success
    const newSuccess = current.successCount + (isSuccess ? 1 : 0);
    const successRate = (newSuccess / Math.max(1, current.usageCount)) * 100;

    // Composite: 40% retention + 30% CTR + 30% success rate
    const score = Math.min(100, Math.max(0, Math.round(
      retention * 0.4 + ctr * 0.3 + successRate * 0.3,
    )));

    await db.update(creativeLibrary).set({
      avgRetention:     retention,
      avgCtr:           ctr,
      successCount:     newSuccess,
      performanceScore: score,
      updatedAt:        sql`now()`,
    }).where(eq(creativeLibrary.id, itemId));

    logger.info(`[CreativeLibrary] Performance updated for item ${itemId}: score=${score} (ret=${retention.toFixed(1)}% ctr=${ctr.toFixed(1)}%)`);
  } catch (err: any) {
    logger.warn(`[CreativeLibrary] recordPerformance failed: ${err?.message}`);
  }
}

// ── Soft-activate / retire ────────────────────────────────────────────────────

export async function setItemActive(itemId: number, active: boolean): Promise<void> {
  await db.update(creativeLibrary)
    .set({ active, updatedAt: sql`now()` })
    .where(eq(creativeLibrary.id, itemId));
}

// ── List items for the library UI ─────────────────────────────────────────────

export async function listLibraryItems(
  channelId: number,
  type?: string,
  includeInactive = false,
) {
  const conditions = [eq(creativeLibrary.channelId, channelId)];
  if (type) conditions.push(eq(creativeLibrary.type, type));
  if (!includeInactive) conditions.push(eq(creativeLibrary.active, true));

  return db
    .select()
    .from(creativeLibrary)
    .where(and(...conditions))
    .orderBy(desc(creativeLibrary.performanceScore), desc(creativeLibrary.createdAt));
}

// ── Library stats for UI summary ─────────────────────────────────────────────

export async function getLibraryStats(channelId: number) {
  const items = await listLibraryItems(channelId, undefined, true);
  const byType: Record<string, number> = {};
  for (const item of items) {
    byType[item.type] = (byType[item.type] ?? 0) + 1;
  }
  const active = items.filter(i => i.active);
  const avgScore = active.length
    ? Math.round(active.reduce((s, i) => s + i.performanceScore, 0) / active.length)
    : 0;
  return {
    total: items.length,
    active: active.length,
    avgScore,
    byType,
    topPerformer: active.sort((a, b) => b.performanceScore - a.performanceScore)[0] ?? null,
  };
}
