import { createLogger } from "../lib/logger";

const logger = createLogger("policy-packs");

export interface PolicyPackRule {
  id: string;
  category: string;
  name: string;
  description: string;
  severity: "info" | "warning" | "critical";
  enforcement: "block" | "warn" | "auto-fix";
  keywords: string[];
  check?: (content: ContentCheckInput) => PolicyViolation | null;
}

export interface PolicyPackLimits {
  titleMaxLength: number;
  descriptionMaxLength: number;
  maxTags: number;
  maxTagLength?: number;
  maxVideoLength?: number;
  minVideoLength?: number;
  thumbnailMaxSize?: string;
}

export interface DisclosureRequirement {
  id: string;
  triggerType: string;
  required: boolean;
  format: string;
  placement: string;
  platformMechanism?: string;
}

export interface AiDisclosureRule {
  required: boolean;
  triggerKeywords: string[];
  disclosureLabel: string;
  platformMechanism?: string;
  description: string;
}

export interface PolicyPack {
  platform: string;
  version: string;
  lastUpdated: string;
  limits: PolicyPackLimits;
  disclosures: DisclosureRequirement[];
  aiDisclosure: AiDisclosureRule;
  rules: PolicyPackRule[];
  contentRestrictions: string[];
}

export interface ContentCheckInput {
  title?: string;
  description?: string;
  tags?: string[];
  hasAiContent?: boolean;
  hasSponsoredContent?: boolean;
  hasAffiliateLinks?: boolean;
  originTypes?: string[];
  platform: string;
}

export interface PolicyViolation {
  ruleId: string;
  ruleName: string;
  severity: "info" | "warning" | "critical";
  enforcement: "block" | "warn" | "auto-fix";
  description: string;
  recommendation: string;
  autoFix?: { field: string; original: string; fixed: string };
}

const YOUTUBE_PACK: PolicyPack = {
  platform: "youtube",
  version: "2026.03",
  lastUpdated: "2026-03-01",
  limits: {
    titleMaxLength: 100,
    descriptionMaxLength: 5000,
    maxTags: 30,
    maxTagLength: 500,
    thumbnailMaxSize: "2MB",
  },
  disclosures: [
    { id: "yt-paid-promo", triggerType: "sponsored", required: true, format: "YouTube Paid Promotion checkbox + text", placement: "video settings + description top", platformMechanism: "Paid Promotion checkbox" },
    { id: "yt-affiliate", triggerType: "affiliate", required: true, format: "Clear text disclosure", placement: "description top", platformMechanism: "none" },
  ],
  aiDisclosure: {
    required: true,
    triggerKeywords: ["ai generated", "ai voice", "ai avatar", "synthetic media", "deepfake", "ai-generated", "generated by ai"],
    disclosureLabel: "Altered or synthetic content",
    platformMechanism: "YouTube Studio > Content > Edit > Show More > Altered Content",
    description: "YouTube requires creators to disclose when realistic AI-generated or synthetic content could be mistaken for real events or people",
  },
  rules: [
    { id: "yt-title-len", category: "metadata", name: "Title length", description: "Title must not exceed 100 characters", severity: "warning", enforcement: "auto-fix", keywords: [] },
    { id: "yt-tag-spam", category: "metadata", name: "Tag spam prevention", description: "Tags must be relevant and not exceed limits", severity: "warning", enforcement: "warn", keywords: ["sub4sub", "view4view", "like4like", "follow4follow"] },
    { id: "yt-misleading", category: "content_policy", name: "Misleading metadata", description: "Titles and thumbnails must accurately represent content", severity: "critical", enforcement: "block", keywords: ["clickbait", "misleading", "fake"] },
    { id: "yt-reused", category: "content_policy", name: "Reused content", description: "Content must be original or transformative", severity: "critical", enforcement: "block", keywords: ["reupload", "re-upload", "stolen", "ripped"] },
    { id: "yt-made-for-kids", category: "coppa", name: "COPPA compliance", description: "Child-directed content must be properly marked", severity: "critical", enforcement: "block", keywords: ["for kids", "toy review", "nursery rhyme", "cartoon for kids"] },
  ],
  contentRestrictions: ["violence_graphic", "hate_speech", "harassment", "dangerous_acts", "spam", "scam", "sexually_explicit"],
};

const TWITCH_PACK: PolicyPack = {
  platform: "twitch",
  version: "2026.03",
  lastUpdated: "2026-03-01",
  limits: {
    titleMaxLength: 140,
    descriptionMaxLength: 2000,
    maxTags: 10,
  },
  disclosures: [
    { id: "tw-sponsored", triggerType: "sponsored", required: true, format: "#ad or Sponsored stream label", placement: "title or stream info", platformMechanism: "Stream Manager > Brand Content toggle" },
  ],
  aiDisclosure: {
    required: true,
    triggerKeywords: ["ai generated", "ai voice", "synthetic", "deepfake"],
    disclosureLabel: "AI-Generated Content",
    description: "Twitch requires disclosure of AI-generated or synthetic content in streams",
  },
  rules: [
    { id: "tw-simulcast", category: "streaming", name: "Simulcast rules", description: "Twitch Partners have simulcast restrictions during contract period", severity: "warning", enforcement: "warn", keywords: ["simulcast", "multi-stream"] },
    { id: "tw-dmca", category: "copyright", name: "DMCA compliance", description: "Do not stream copyrighted music without license", severity: "critical", enforcement: "block", keywords: ["dmca", "unlicensed music", "copyrighted song"] },
    { id: "tw-viewbot", category: "integrity", name: "View manipulation", description: "Artificial view inflation is prohibited", severity: "critical", enforcement: "block", keywords: ["viewbot", "follow bot", "bot viewers"] },
  ],
  contentRestrictions: ["hate_raid", "harassment", "sexual_content", "gambling_unlicensed"],
};

const TIKTOK_PACK: PolicyPack = {
  platform: "tiktok",
  version: "2026.03",
  lastUpdated: "2026-03-01",
  limits: {
    titleMaxLength: 2200,
    descriptionMaxLength: 2200,
    maxTags: 30,
    maxVideoLength: 600,
    minVideoLength: 1,
  },
  disclosures: [
    { id: "tt-branded", triggerType: "sponsored", required: true, format: "Branded Content toggle + disclosure text", placement: "video settings", platformMechanism: "Branded Content toggle in post settings" },
    { id: "tt-affiliate", triggerType: "affiliate", required: true, format: "Clear text disclosure", placement: "caption", platformMechanism: "none" },
  ],
  aiDisclosure: {
    required: true,
    triggerKeywords: ["ai generated", "ai voice", "synthetic", "deepfake", "ai avatar"],
    disclosureLabel: "AI-generated content",
    platformMechanism: "TikTok AI content label in creation tools",
    description: "TikTok requires labeling of AI-generated content that depicts realistic scenes",
  },
  rules: [
    { id: "tt-minor-safety", category: "safety", name: "Minor safety", description: "Content involving minors has strict rules", severity: "critical", enforcement: "block", keywords: ["child", "minor", "underage"] },
    { id: "tt-misinfo", category: "content_policy", name: "Misinformation", description: "False or misleading claims are prohibited", severity: "critical", enforcement: "block", keywords: ["fake news", "conspiracy", "hoax"] },
  ],
  contentRestrictions: ["hate_speech", "violence", "dangerous_challenge", "misinformation", "fake_engagement"],
};

const X_PACK: PolicyPack = {
  platform: "x",
  version: "2026.03",
  lastUpdated: "2026-03-01",
  limits: {
    titleMaxLength: 280,
    descriptionMaxLength: 25000,
    maxTags: 10,
  },
  disclosures: [
    { id: "x-ad", triggerType: "sponsored", required: true, format: "#ad or #sponsored", placement: "post text", platformMechanism: "none" },
  ],
  aiDisclosure: {
    required: true,
    triggerKeywords: ["ai generated", "deepfake", "synthetic"],
    disclosureLabel: "AI-generated label",
    description: "X requires AI-generated media to be labeled",
  },
  rules: [
    { id: "x-manipulation", category: "integrity", name: "Platform manipulation", description: "Artificial engagement is prohibited", severity: "critical", enforcement: "block", keywords: ["buy followers", "bot engagement", "fake likes"] },
  ],
  contentRestrictions: ["hate_speech", "violence_glorification", "manipulation"],
};

const INSTAGRAM_PACK: PolicyPack = {
  platform: "instagram",
  version: "2026.03",
  lastUpdated: "2026-03-01",
  limits: {
    titleMaxLength: 2200,
    descriptionMaxLength: 2200,
    maxTags: 30,
  },
  disclosures: [
    { id: "ig-branded", triggerType: "sponsored", required: true, format: "Branded Content tag", placement: "post header", platformMechanism: "Branded Content tag in post settings" },
  ],
  aiDisclosure: {
    required: true,
    triggerKeywords: ["ai generated", "synthetic", "deepfake"],
    disclosureLabel: "Made with AI",
    platformMechanism: "Meta AI content labels",
    description: "Instagram auto-labels AI-generated images and requires disclosure",
  },
  rules: [
    { id: "ig-engagement-bait", category: "integrity", name: "Engagement bait", description: "Artificially inflating engagement is prohibited", severity: "warning", enforcement: "warn", keywords: ["like for like", "follow back", "engagement pod"] },
  ],
  contentRestrictions: ["nudity", "hate_speech", "violence", "self_harm"],
};

const KICK_PACK: PolicyPack = {
  platform: "kick",
  version: "2026.03",
  lastUpdated: "2026-03-01",
  limits: {
    titleMaxLength: 200,
    descriptionMaxLength: 5000,
    maxTags: 10,
  },
  disclosures: [
    { id: "kick-sponsored", triggerType: "sponsored", required: true, format: "Disclosure in title or stream info", placement: "title", platformMechanism: "none" },
  ],
  aiDisclosure: {
    required: false,
    triggerKeywords: ["ai generated"],
    disclosureLabel: "AI Content",
    description: "Kick encourages but does not strictly require AI content disclosure",
  },
  rules: [
    { id: "kick-gambling", category: "content_policy", name: "Gambling content", description: "Gambling streams must comply with local regulations", severity: "warning", enforcement: "warn", keywords: ["gambling", "slots", "casino", "betting"] },
  ],
  contentRestrictions: ["hate_speech", "harassment", "illegal_activity"],
};

const RUMBLE_PACK: PolicyPack = {
  platform: "rumble",
  version: "2026.03",
  lastUpdated: "2026-03-01",
  limits: {
    titleMaxLength: 100,
    descriptionMaxLength: 5000,
    maxTags: 20,
  },
  disclosures: [
    { id: "rumble-sponsored", triggerType: "sponsored", required: true, format: "Disclosure text", placement: "description", platformMechanism: "none" },
  ],
  aiDisclosure: {
    required: false,
    triggerKeywords: ["ai generated", "synthetic"],
    disclosureLabel: "AI Content",
    description: "Rumble encourages disclosure of AI-generated content",
  },
  rules: [
    { id: "rumble-copyright", category: "copyright", name: "Copyright compliance", description: "Content must not infringe copyright", severity: "critical", enforcement: "block", keywords: ["copyright", "dmca"] },
  ],
  contentRestrictions: ["illegal_content", "threats"],
};

const POLICY_PACKS: Record<string, PolicyPack> = {
  youtube: YOUTUBE_PACK,
  twitch: TWITCH_PACK,
  tiktok: TIKTOK_PACK,
  x: X_PACK,
  instagram: INSTAGRAM_PACK,
  kick: KICK_PACK,
  rumble: RUMBLE_PACK,
};

export function getPolicyPack(platform: string): PolicyPack | null {
  return POLICY_PACKS[platform] || null;
}

export function getAllPolicyPacks(): PolicyPack[] {
  return Object.values(POLICY_PACKS);
}

export function getSupportedPlatforms(): string[] {
  return Object.keys(POLICY_PACKS);
}

export function checkContentAgainstPack(content: ContentCheckInput): {
  compliant: boolean;
  violations: PolicyViolation[];
  warnings: PolicyViolation[];
  gatesChecked: string[];
} {
  const pack = POLICY_PACKS[content.platform];
  if (!pack) {
    return { compliant: true, violations: [], warnings: [], gatesChecked: [] };
  }

  const violations: PolicyViolation[] = [];
  const warnings: PolicyViolation[] = [];
  const gatesChecked: string[] = [];

  gatesChecked.push("title_length");
  if (content.title && content.title.length > pack.limits.titleMaxLength) {
    const v: PolicyViolation = {
      ruleId: `${content.platform}-title-len`,
      ruleName: "Title length",
      severity: "warning",
      enforcement: "auto-fix",
      description: `Title exceeds ${pack.platform} limit of ${pack.limits.titleMaxLength} chars (${content.title.length})`,
      recommendation: `Shorten title to ${pack.limits.titleMaxLength} characters`,
      autoFix: {
        field: "title",
        original: content.title,
        fixed: content.title.substring(0, pack.limits.titleMaxLength - 3) + "...",
      },
    };
    warnings.push(v);
  }

  gatesChecked.push("description_length");
  if (content.description && content.description.length > pack.limits.descriptionMaxLength) {
    warnings.push({
      ruleId: `${content.platform}-desc-len`,
      ruleName: "Description length",
      severity: "warning",
      enforcement: "auto-fix",
      description: `Description exceeds ${pack.platform} limit of ${pack.limits.descriptionMaxLength} chars`,
      recommendation: `Shorten description to ${pack.limits.descriptionMaxLength} characters`,
    });
  }

  gatesChecked.push("tag_limit");
  if (content.tags && content.tags.length > pack.limits.maxTags) {
    warnings.push({
      ruleId: `${content.platform}-tag-limit`,
      ruleName: "Tag limit",
      severity: "warning",
      enforcement: "warn",
      description: `Too many tags (${content.tags.length}/${pack.limits.maxTags})`,
      recommendation: `Reduce tags to ${pack.limits.maxTags} or fewer`,
    });
  }

  gatesChecked.push("ai_disclosure");
  if (content.hasAiContent && pack.aiDisclosure.required) {
    const fullText = [content.title, content.description].filter(Boolean).join(" ").toLowerCase();
    const hasDisclosure = pack.aiDisclosure.triggerKeywords.some(kw => fullText.includes(kw)) ||
      fullText.includes("ai-generated") || fullText.includes("made with ai");
    if (!hasDisclosure) {
      violations.push({
        ruleId: `${content.platform}-ai-disclosure`,
        ruleName: "AI Content Disclosure",
        severity: "critical",
        enforcement: "block",
        description: `AI-generated content requires disclosure on ${pack.platform}: "${pack.aiDisclosure.disclosureLabel}"`,
        recommendation: pack.aiDisclosure.platformMechanism
          ? `Use ${pack.aiDisclosure.platformMechanism} to add the disclosure`
          : `Add "${pack.aiDisclosure.disclosureLabel}" disclosure to your content`,
      });
    }
  }

  gatesChecked.push("sponsorship_disclosure");
  if (content.hasSponsoredContent) {
    const sponsorDisclosure = pack.disclosures.find(d => d.triggerType === "sponsored");
    if (sponsorDisclosure?.required) {
      const fullText = [content.title, content.description].filter(Boolean).join(" ").toLowerCase();
      const hasDisclosure = ["#ad", "#sponsored", "#partner", "paid promotion", "sponsored by"].some(d => fullText.includes(d));
      if (!hasDisclosure) {
        violations.push({
          ruleId: sponsorDisclosure.id,
          ruleName: "Sponsorship Disclosure",
          severity: "critical",
          enforcement: "block",
          description: `Sponsored content requires proper disclosure on ${pack.platform}`,
          recommendation: `Add disclosure: ${sponsorDisclosure.format}. Placement: ${sponsorDisclosure.placement}`,
        });
      }
    }
  }

  gatesChecked.push("content_rules");
  const fullText = [content.title, content.description, ...(content.tags || [])].filter(Boolean).join(" ").toLowerCase();
  for (const rule of pack.rules) {
    if (rule.keywords.length === 0) continue;
    const matchedKeywords = rule.keywords.filter(kw => fullText.includes(kw.toLowerCase()));
    if (matchedKeywords.length > 0) {
      const v: PolicyViolation = {
        ruleId: rule.id,
        ruleName: rule.name,
        severity: rule.severity,
        enforcement: rule.enforcement,
        description: `${rule.description} — matched: ${matchedKeywords.join(", ")}`,
        recommendation: `Review content for ${rule.name} compliance`,
      };
      if (rule.severity === "critical") {
        violations.push(v);
      } else {
        warnings.push(v);
      }
    }
  }

  return {
    compliant: violations.length === 0,
    violations,
    warnings,
    gatesChecked,
  };
}

export function getPolicyPackHash(platform: string): string {
  const pack = POLICY_PACKS[platform];
  if (!pack) return "";
  const content = JSON.stringify({
    version: pack.version,
    limits: pack.limits,
    rules: pack.rules.map(r => ({ id: r.id, severity: r.severity, keywords: r.keywords })),
    disclosures: pack.disclosures,
    aiDisclosure: pack.aiDisclosure,
  });
  let hash = 0;
  for (let i = 0; i < content.length; i++) {
    const chr = content.charCodeAt(i);
    hash = ((hash << 5) - hash) + chr;
    hash |= 0;
  }
  return `${platform}:${pack.version}:${Math.abs(hash).toString(36)}`;
}
